sorrycc/awesome-javascript

README.md
Nice plugin for styling checkboxes and radio-buttons.
=> Ion.CheckRadio jQuery plugin

README.md
[pica](https://github.com/nodeca/pica)
High quality image resize (with fast Lanczos filter, implemented in pure JS).
=> Add `pica`

README.md
[riot](https://github.com/riot/riot)
React-like library, but with very small size.
=> Add `riot`

README.md
Jade is a terse language for writing HTML templates.
Produces HTML
Supports dynamic code
Supports reusability (DRY)
=> Added JadeJs Templating Engines

README.md
Added a comma in README.md for [Sinon.JS](https://github.com/cjohansen/Sinon.JS) to provide more clarification.
BEFORE: 
AFTER:
=> [Sinon.JS](https://github.com/cjohansen/Sinon.JS) - README.md

README.md
ClassManager uses unique inheritance model: it renames parent methods in child's prototype.
Also it has separate repository with high-quality speed tests for class systems...
=> Added ClassManager

README.md
Suggest to add DalekJS functional testing tool.
=> Add DalekJS

README.md
=> Add two more module loaders

README.md
Mprogress.js - create four types of Material Design progress linear bars.
=> Mprogress.js-Material Design progress linear bars

README.md
=> Adding Datatables

README.md
Added Vibrant.js to the library
=> Added Vibrant.js to the library

README.md
"E" is for "effective." EJS is a simple templating language that lets you generate HTML markup with plain JavaScript. No religiousness about how to organize things. No reinvention of iteration and control-flow. It's just plain JavaScript.
=> Added EJS Template Engine

README.md
=> Add Semantic UI

README.md
Added Dynamic.js  , Javascript library to create physics-based CSS animations.
=> Added Dynamic.js

README.md
=> Added jQuery contextMenu

README.md
=> Added Slideout.js

README.md
Add npm to package manager
Fixes #139
=> browserify and webpack should be bundlers

README.md
Added ScrollMenu , Demo: http://ignitersworld.com/lab/scrollmenu/
=> Added ScrollMenu

README.md
added reference to yolpo under Testing Framework / Runner
=> added reference to yolpo

README.md
=>  Remove express.js because definition of this repo - #153, #145

README.md
Added a nice site for creating and testing RegEx in js
=> Added regex101 for js regex validation/testing

README.md
https://github.com/marko-js/marko
marko has some unique and awesome features:
- [Extremely fast](https://github.com/marko-js/templating-benchmarks)
- Lightweight (~3.75KB gzipped)
- Works on the server (Node.js) and in the browser
- Clean HTML syntax
- Custom tags and custom attributes
- Streaming, async and progressive HTML rendering
- Compiles templates to CommonJS modules that are [readable and debuggable](https://gist.github.com/patrick-steele-idem/0514b480219d1c9ed8d4)
- Server-side and client-side rendering (compatible with JavaScript module bundlers)
- Friendly compile-time error messages
- Can be used with [marko-widgets](https://github.com/marko-js/marko-widgets) for building stateful UI components with DOM diffing/patch, event delegation and declarative event binding
Sample …
=> Add `marko` to `Templating Engines`

README.md
Currently more than 1.000 stars :) https://github.com/zzarcon/focusable.
Thanks for the repo!!
=> Add 'Focusable' to 'Tours And Guides'

README.md
I decided to add the main cms frameworks in this PR instead of PR'ing each one.
=> Fixes 181, adding node-powered cms framework section

README.md
I wasn't sure if it should be in functional programming or FRP, because it advertises itself as neither. But it shares a lot of the same functionality as kefir and co.
=> add highland

README.md
I have used this micro library with great success in various frontend projects.
=> Add minilog as a logging tool

README.md
**[url-pattern](https://github.com/snd/url-pattern) is easier than regex string matching for urls, domains, filepaths and other strings. turn strings into data or data into strings.**
information about package heath, features and examples are at the top of the readme followed by thorough documentation.
http://nmotw.in/url-pattern/
=> add `url-pattern` to category `String`

README.md
* adds 4 slider libraries
* add prettyembed.js in a new audio/video section
=> add Audio/Video tools in new section, sliders, list.js and slider libs

README.md
Add information about OpenLayers3 lib
=> Add openlayers to maps

README.md
Hi,
sorry for pulling 4 links at once. I wanted to make it easier for both of us. If you really don't want to add one of them, I'll change it, but hope it's fine this way.
I added 3 of the links to the number-section. Maybe it would make more sense to add a "Math" section.
Thanks,
Robert
=> Added infusion libraries

README.md
A simple jQuery image cropping plugin.
=> Update cropper to images processing

README.md
hopefully up to your standards in terms of awesome.
https://github.com/mkoryak/floatThead
=> add floatThead to Table/Grid

README.md
- [RegExr](http://regexr.com)
- [RegExpBuilderJs](https://github.com/thebinarysearchtree/regexpbuilderjs)
=> Add RegExr & RegExpBuilder to RegExp section

README.md
[https://github.com/lrsjng/modulejs](https://github.com/lrsjng/modulejs)
=> add modulejs as module system to Readme.md

README.md
Not specifically 'awesome', but might be better for some from an engineering standpoint.
=> + other list: you-might-not-need-jquery-plugins

README.md
=> Added Spotify SDK

README.md
I've created an awesome list of lists of interview question for the most of popular technologies/frameworks/languages. If you think that it is awesome, merge it :shipit:
=> Add awesome interview questions repository link

README.md
Read more https://clusterize.js.org/
=> Added Clusterize.js to Scroll category

README.md
=> Add jq-cookie #231

README.md
I enjoy using this template engine and wanted to share! Thanks for the opportunity to contribute.
=> Added Swig to Templating Engines

README.md
Added Trumbowyg by Alex-D
https://alex-d.github.io/Trumbowyg/
=> Add Trumbowyg

README.md
Added chance.js under numbers section. It has the ability to generate various types of random numbers. (Float, natural, int etc.)
=> Added chance.js

README.md
An awesome replacement for JavaScript's alert.
=> Add SweetAlert

README.md
Just thought I would share an awesome Javascript podcast!
=> Add Podcast

README.md
Thought this would be a sensible addition. That said, since it's based on React I can understand if someone thinks it's not a good fit.
=> Added Facebook's Draft.js

README.md
Added Storyboard to the Log section. I believe it is a good complement to the libraries that are already there, and provides some original functionality: the ability to see all client and server logs in a single place, in a hierarchical way, and even show server tasks within client-side stories.
=> Add storyboard

README.md
A minimalist real-time JavaScript framework for tomorrow's apps.
http://feathersjs.com/
=> Add feathers

README.md
* merge media/audio/video sections
* remove daux.io (php app)
* add misc utils/libraries
* add audio/video libs
* fix spacing
* add boilerplates and typography sections
* deindent gestures section
* add editors, sliders, input, tooltip, lightbox, grid, animation and misc libs
* add link to awesome-css
* move some entries to more appropriate sections
* add clappr
=> misc fixes and additions

README.md
Missed "r": impess.js => impress.js
=> Fix impress.js's name

README.md
=> correction - names of commercial dataviz libraries

README.md
Cycle.js is a semi-framework with some new ideas.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sorrycc/awesome-javascript/296)
=> Add Cycle.js

README.md
Recharts is a charting library built on React and D3. Couldn't find an entry for it in visualization tools, so I propose it to be added.
=> Add recharts to Data Visualization

README.md
Added 'fecha' date library as a lightweight replacement for parsing and formatting functionalities of moment.js
Link: [https://github.com/taylorhakes/fecha](https://github.com/taylorhakes/fecha)
=> Date library - fecha

README.md
=> add preludejs

README.md
i've added missing nativescript
=> add [awesome]nativescript to the list

README.md
Tape is a great library for testing, keeping it simple and straightforward. Definitely worth listing.
=> Add tape test library

README.md
AvaJS - 🚀 Futuristic JavaScript test runner
=> Add Ava Testing Framework

README.md
Add [HyperApp](https://github.com/hyperapp/hyperapp).
EDIT: Fix link.
=> Add HyperApp.

README.md
want to add prettier to the QA section. Thanks!
=> add prettier to QA

README.md
Add library voca for manipulate string.
=> add vocajs

README.md
Hello,
I am Saurabh, co-founder of Hackr.io. Hackr.io is a programming community & a great place to find the best online programming courses and tutorials. It's a one stop solution for tutorial recommendations with 5000+ tutorial of more than 140 programming languages.
I was looking at your learning resources page and found it pretty useful. I believe that Hackr.io would be really useful to the developer community in finding the right programming course/tutorial and would make a nice addition to your resource page.
Hackr is also listed on other esteemed websites like Lehigh University's resource page and official Official Python wiki page to name a few.
Thanks for the list of great resources you have compiled. Enjoy your week:)
=> A suggestion for a resource addition

README.md
=> fix markdown link syntax errors

README.md
This is a great project! I worked on a couple of ways to search javascript documentation, the array explorer and object explorer. It's a way to find the right method without clicking through the docs one by one. Let me know if you think it belongs in another category. Thank you!
=> Add in array and object explorer

README.md
I found these articles about JavaScript's engine, stacks and similar topics. I think it would be useful especially for anyone dealing with memory in JavaScript.
=> Add a new series of articles "How JavaScript works" by SessionStack

README.md
=> Add Rails Ranger

README.md
Add [atvjs](https://github.com/emadalam/atvjs) framework to the list 🙏
=> Add atvjs to MVC frameworks and Libraries section

README.md
A lightweight JavaScript library for creating particles.
=> Add particles.js

README.md
=> Add anime.js and mo.js

README.md
https://clipboardjs.com/
https://github.com/zenorocha/clipboard.js/
=> Add 'clipboard.js' to Misc section

README.md
Possibly the best resource to REALLY learn JavaScript, by an outstanding author
Hope you find this useful
=> Added YDKJS to the Worth Reading list

README.md
Added new category generators and placed inside gatsby.js
=> add gatsby.js

README.md
=> update you-might-not-need-jquery-plugins to master repo

README.md
Very simple JavaScript library that gives your website parallax animations on any images.
=> add simpleParallax JS library

README.md
[Embla Carousel](https://github.com/davidcetinkaya/embla-carousel) - An extensible low level carousel for the web, written in TypeScript.
=> Add Embla Carousel

README.md
More info here: https://jgraph.github.io/mxgraph/
=> Added mxGraph - diagramming library.

README.md
Realized I wasn't seeing any payment/financial SDK's so I suggested a Node.js SDK for taking payments.
=> Square Node.js SDK suggestion added

README.md
Thanks for the awesome list & consideration! 
About:
[analytics](https://www.npmjs.com/package/analytics) is a lightweight, extendable analytics library designed to work with any third-party analytics provider to track page views, custom events, & identify users.
Repo: https://github.com/davidwells/analytics
Docs: https://getanalytics.io/
=> Add `analytics` npm module

README.md
=> docs: add dayjs for date

README.md
Add navaid router from https://github.com/lukeed/navaid
=> add navaid router

README.md
Add `wretch` package. An alternative to `axios`.
**Github:** [https://github.com/elbywan/wretch](https://github.com/elbywan/wretch)
=> Add wretch

README.md
It's not my project, but it's useful
=> Add plexis

README.md
Link to Functional-Light JavaScript book by Kyle Simpson.
=> add link to Functional-Light JavaScript - reading

README.md
Add Bearer.sh API Client for JS. It helps dealing with APIs that requires OAuth2 / API Key / Basic authentication methods.
=> Add Bearer.sh API Client

README.md
Summernote is a JavaScript library that helps you create WYSIWYG editors online.
Home page: https://summernote.org
Github: https://github.com/summernote/summernote
=> Add Summernote

README.md
Lightweight cross-platform Neural Network library
https://github.com/mrdimosthenis/Synapses
=> add Synapses to Machine Learning

README.md
Just a quick addition for Cypress since I noticed it was missing.
=> Add Cypress testing framework

README.md
Ink-components is a self-contained javascript script that can be included in any HTML page to add web-components (new HTML tags) to make dynamic text and variables that the user can change.
Here is a demo:
More at: https://components.ink/
Repository: https://github.com/ink-components/ink-components
I have no link with the software except that I have discovered it today and find it amazing, it is very simple to use, is highly portable and allows to easily create explorable explanations essays.
=> Add ink-components in Misc

README.md
Idyll is a markup language and toolkit for writing interactive articles. It allows to create explorable explanations and interactive storytelling essays.
Demo and more infos: https://idyll-lang.org/
Repository: https://github.com/idyll-lang/idyll
There is also an [embeddable .js here](https://github.com/idyll-lang/idyll-embed) that doesn't require npm, and an [IDE in alpha here](https://github.com/idyll-lang/idyll-studio).
I have no link with the software except that I have discovered it today and find it amazing. It is a bit more involving to use than ink-components, but it is a really complete piece of software to create explorable explanations, and is backed by an excellent lab working on data visualization who published a [paper about …
=> Add Idyll in Misc

README.md
[EHTML](https://github.com/Guseyn/EHTML) - HTML Framework that allows you not to write JavaScript code. It  can be described as a set of custom elements that you can put on HTML page for different purposes and use cases. The main idea and goal of this library is to provide a convenient way to get rid of JavaScript code on the client side as much as it's possible for basic and routine stuff. Hopefully, you might find it awesome.
=> EHTML as Templating Engine and Framework

README.md
I have updated the link from ink-components to @iooxa/article. Github does redirect, but this is nicer. :)
Let me know if you need anything else!
=> Updated link after the repository moved

README.md
Added three open source libraries built by [Frappe](https://github.com/frappe).
=> feat: added frappe charts, gantt and datatable

README.md
[husky](https://www.npmjs.com/package/husky)
=> feat: husky

README.md
=> add particles-bg

README.md
More info at 
https://github.com/getgauge/taiko
=> Recommend Taiko

README.md
[Article ] Multi-threading using web-workers
=> [Article ] Multi-threading using web-workers

README.md
Video/Audio
AmplitudeJS
https://521dimensions.com/open-source/amplitudejs
=> Add AmplitudeJS

README.md
https://github.com/alpinejs/alpine
=> Add alpine.js

README.md
=> Added Quaternion.js

README.md
Github: https://github.com/infernojs/inferno
=> Add inferno

README.md
=> Add an open source spreadsheet-Luckysheet

README.md
Hey @sorrycc 
just fixing the link to GraphicsJS.
Cheers!
=> Fixing link to GraphicsJS

README.md
https://github.com/concentjs/concent
=> Added concent library

README.md
https://github.com/fuse-box/fuse-box
=> Added FuseBox Bundler

README.md
[javascript-algorithms](https://github.com/trekhleb/javascript-algorithms) is a repository with a collection of algorithms and data structures implemented in JavaScript with explanations and links to further readings. It might be a good fit for the `awesome-javascript` list since the audience of this repo is JS-oriented and `javascript-algorithms` could help with preparing for the JS tech interviews.
=> Adding javascript-algorithms to misc section.

README.md
Snowpack’s unbundled development is one of the most popular JavaScript’s native ES Module (ESM) syntax implementation.
=> Adding Snowpack to Bundlers section.

README.md
=> docs: add G2, G2Plot

README.md
Add Foal framework to the list.
_Description_: Elegant and all-inclusive Node.JS framework for building web applications (TypeScript)
_Website_: https://foalts.org/
_Github_: https://github.com/FoalTS/foal
_Stars_: > 1k
_Activity_: regular updates and improvements since 3 years
More than 11,000 lines of _documentation_ on the website.
=> Add FoalTS to framework list

README.md
- Mark angular.js as deprecated
- Add angular link
- Add luxon link
=> Add angular and luxon

README.md
Checklist:
---
The new addition is a Hooks for fetching, caching, and updating asynchronous data in React, it's super cool/easy to use for any react dev or js guy, it's quite popular and actively maintained too. that's why I think it should be included here.
=> add react-query to API list

README.md
Checklist:
---
It's a WCAG 2.1 complaint Date picker to have a good alternative when accesibility it's pursued.
=> Add Duet date picker

.github/workflows/validator.yml, README.md
Title explains it all. 
Cheers,
G.
=> feat: introduce github actions

README.md
Checklist:
**Adonis js is a fully featured web framework for Node.js**. It **includes everything you need to create a fully functional web app or an API server**. Stop wasting hours in downloading and assembling hundreds of packages together — Use AdonisJS and be productive from day one.
=> Add Adonisjs to MVC Frameworks and Libraries

README.md
=> Add few libraries related to web builders, graph, visual programming

README.md
Checklist:
---
Notifire is an open-source notification infrastructure, it allows developers to create multi channel notification with a single API.
...
=> Add Notifire as a notification infrastructure

README.md
Checklist:
---
Playwright is a Node.js library to automate Chromium, Firefox and WebKit with a single API. Playwright is built to enable cross-browser web automation that is ever-green, capable, reliable and fast.
...
=> Add Playwright

README.md
Checklist:
---
`m2cgen` is a lightweight library with command line interface which allows to transpile trained machine learning models into a native code of  JavaScript programming language.
Examples of generated JS code can be found [here](https://github.com/BayesWitnesses/m2cgen/tree/master/generated_code_examples/javascript).
=> Add m2cgen for transpiling ML models into JS code

README.md
This is fixing some outdated links, found with [deadlink](https://github.com/nschloe/deadlink).
```
deadlink check README.md
```
=> update a bunch of links

README.md
Checklist:
---
Million can be used as a MVC Framework/Library, and is used to build MVC Frameworks/Libraries.
[GitHub Repository](https://github.com/aidenybai/million) | [Documentation](https://million.js.org)
=> Add Million.js

README.md
Checklist:
---
...
Vest is a form validation framework inspired by unit testing libraries. Fits well in the validation section.
=> Add Vest validation framework

README.md
There's no section dedicated to game engines despite that there are many of them and most of them are quite popular
=> Added game engines section

README.md
Jspreadsheet is a lightweight vanilla javascript plugin to create amazing web-based online interactive tables and spreadsheets compatible with other spreadsheet software. You can create an online spreadsheet table from a JS array, JSON, CSV or XSLX files. You can copy from excel and paste straight to your online spreadsheet and vice versa. It is very easy to integrate any third party javascript plugins to create your own custom columns, custom editors, and customize any feature into your application. Jspreadsheet has plenty of different input options through its native column types to cover the most common web-based application requirements. It is a complete solution for web data management. Create amazing online spreadsheets with Jspreadsheet.
Checklist:
---
...
=> Add Jspreadsheet CE

README.md
Checklist:
- [x ] I've read and understood [Contributing Guidelines](CONTRIBUTING.md).
---
As the loader is not developed anymore, it should be removed from the list.
...
=> Development of curl has stopped.

README.md
Checklist:
---
This adds [`wild-wild-path`](https://github.com/ehmicky/wild-wild-path).
This library provides with CRUD (get/has/list/set/remove) operations on object properties using not only dot-delimited paths but also wildcards (`*` and `**`), regular expressions, array slices and unions. 
The methods are purely functional and higher-level functional utilities are available as a separate project [`wild-wild-utils`](https://github.com/ehmicky/wild-wild-utils).
...
=> Add `wild-wild-path`

README.md
Checklist:
---
This PR adds `awesome-bun` list tailored to the new Bun javascript runtime to the other awesome lists section.
Thank you.
=> add awesome-bun to other awesome lists

README.md
Checklist:
---
SWRV is Stale-while-revalidate data fetching for Vue.
Vue Query is Hooks for fetching, caching and updating asynchronous data in Vue.
=> Add SWRV and Vue Query

README.md
Checklist:
---
Js-sdsl is a javascript standard data structure library implemented with reference to c++ stl and supports c++ bidirectional iterator mode.
=> Add js-sdsl

README.md
Checklist:
---
Whatsup is a modern frontend framework with own reactivity system and JSX components based on pure functions and generators.
=> Add Whatsup

README.md
=> fix: remove usejsdoc.org

README.md
=> Add Google Lovefield to the storage collection

README.md
Checklist:
---
I'm opening this pull request because I'm the author of this package. Currently, `url-state-machine` provides the fastest JavaScript based url parser for node.js. The benchmarks are included in the README.
=> feat: add url-state-machine to string libraries

README.md
Checklist:
---
Adds AutoAnimate, docs available at https://auto-animate.formkit.com.
Project is new, but is a sub-product of FormKit (https://formkit.com) that has been around for a while now and has more than 1300 stars on GitHub. 
Thank you for considering!
...
=> Add AutoAnimate

README.md
Checklist:
---
Added mizizers list
=> Added minimizers

README.md
=> Added Dexie.js to storage.

README.md
Checklist:
---
A more convenient way to use storage through proxy.
=> add proxy-web-storage to storage

README.md
=> add the web-worker section(#842)

README.md
=> feat: add Everright-formEditor

README.md
Checklist:
---
Toastify is one of the easy to use library for toasts.
=> added toastify-js.

README.md
Checklist:
Hi!
Here's a PR to add a section for Javascript transpilers without ECMAScript dependency. I added one of the best transpilers supported by Vercel, and links to related lists.
=> Added new transpilers section and links.

README.md
Checklist:
---
Schedule-X is a project of rising popularity, which aims to complement the current market of calendars, with an event calendar that adheres to the Material Design 3 specification.
...
=> Add schedule-x

README.md
Checklist:
---
Adds [Tempo](https://tempo.formkit.com) — a date library for working with native Date objects with Timezone support, formatting and parsing.
=> Adds Tempo

README.md
Checklist:
---
WebdriverI/O supports E2E and Unit / Component Testing in real Browser! Easy to setup and have extensive list of report, services, easy integration with different cloud platforms.
...
=> added wdio test framework

README.md
Checklist:
---
Roadmap.sh is a 100% free and open-source, community back learning platform that is the #6 project on GitHub.
...
=> Add roadmap.sh/javascript to Worth-Reading

README.md
=> Added Lume - Deno based static site generator

README.md
Checklist:
---
Adding RevoGrid to the Spreadsheet category of the “Awesome JavaScript” list. RevoGrid is designed to address the needs of developers who require a fast, flexible, and feature-rich grid component capable of handling large datasets with ease. I believe RevoGrid would be a great addition to your list.
=> Added RevoGrid library to Spreadsheets

README.md
Checklist:
---
JS-PyTorch is a Deep Learning library, really similar to Python's PyTorch in syntax. It can be used to train and test neural networks on node and on a web browser.
The library is well-mantained and well-documented ([full docs](https://eduardoleao052.github.io/js-pytorch/site/index.html)). It is easy to use and growing in popularity.
...
=> Added JS-PyTorch

README.md
Checklist:
---
This addition includes well-known JavaScript ORMs (Object-Relational Mappers) that simplify database interactions by providing an abstraction layer over SQL and NoSQL databases.
They are widely adopted in modern JavaScript applications, backed by strong community support, and each has garnered thousands of stars on GitHub.
=> Add some ORM packages

README.md
Checklist:
---
...
This PR introduces a new "WebSockets" section to categorize libraries focused on real-time, event-driven communication. As the first addition to this section, I’ve included [Socket.io](https://github.com/socketio/socket.io).
Socket.io is well backed by strong community support, and has garnered thousands of stars on GitHub.
=> Add Websockets section and initialize it with Socket.io

README.md
Added Regex visualizer & editor
Features:
Visualizing regular expressions
Visual editing of regular expressions
Testing of regular expressions
Link: https://github.com/Bowen7/regex-vis
Checklist:
---
...
=> docs(regex-vis): add Regex visualizer & editor

README.md
Added a link to Vite in the bundlers section of the README. Vite is a next-generation frontend tooling optimized for speed and modern development workflows.
Checklist:
---
...
=> docs(md): add Vite link to bundlers list

README.md
=> Add KaibanJS

README.md
Checklist:
---
Stripe Node.js SDK lets you integrate payments, subscriptions, and billing into your JavaScript/TypeScript apps.
Stats:
Repo: [Stripe Node.js SDK](https://github.com/stripe/stripe-node)
Stars: 4.2k
Forks: 842
...
=> Add stripe node to sdk
