- README.md
Hi!
Here's a PR to add a section for ES6-related JavaScript tools. I added two of the best resources and transpilers, and links to related lists.
> Add new ES6 section and links.

- README.md
[babelfish](https://github.com/nodeca/babelfish/)
In 99% of cases "advanced" i18n people just need plurals. Babelfish provides simple notation to support plurals directly in phrases, with zero coding.
> Add `babelfish`

- README.md
[bag.js](https://github.com/nodeca/bag.js)
A caching script and resource loader, similar to `basket.js`, but with additional k/v interface and localStorage / websql / indexedDB support. Difference with `basket.js`:
- `basket.js` use localStorage, that set limit ~1mb for cached data. Can be a problem for big projects and development with not minified assets.
- callbacks instead of promisses.
> Add `bag.js`

- README.md
6to5 is now Babel.
http://babeljs.io/blog/2015/02/15/not-born-to-die/
http://www.infoq.com/news/2015/02/babel-new-name-for-6to5
> Rename 6to5 to Babel

- README.md
We'd be delighted to be included in the list! Our JS docs are here: https://plot.ly/javascript-graphing-library/. We give it away for open projects and license it for commercial projects.
> added plotly to "Data Visualization" list

- README.md
https://github.com/gartz/ObjectEventTarget
It worths because you can set it as prototype of constructor function and all instances will be able to listen for events you can dispatch from inside your object logic, just like you work with DOMElements, what is very well documented and reliable. And you don't need to create any special property in your object it works detecting the context of the object, and easy allow to that object be extended and still work.
Test coverage 99% and documented.
> Add ObjectEventTarget

- README.md
Browserify is not a package manager. It does not fetch packages. It isa  module system for JS. It does what requireJS do in a neater way.
> Move browserify from package managers to loaders

- README.md
Instead of it there is new one Famous, and it is differ from an old famous:
https://github.com/famous/engine
https://github.com/Famous/framework (alpha)
> This version of Famous is deprecated

- README.md
[diff2html](https://github.com/rtfpessoa/diff2html) is an simple parsing library for git diffs that creates a JSON representation of the diff and can also generate pretty HTML.
> Add diff2html to Files

- README.md
Escape HTML tag for visibility, add a full stop.
> Fix typos in picturefill description

- README.md
timeago.js is a simple library (less then 2kb) used to format date with `*** time ago` statement. eg: '3 hours ago'.
> add timeago.js

- README.md
A message on the [BootstrapValidator README](https://github.com/nghuuphuoc/bootstrapvalidator/blob/master/README.md) says that the project is no longer supported.  The project is now maintained under the name FormValidation.
> Update unsupported BootstrapValidator link to point to renamed FormValidation

- README.md
The link was already changed but the name wasn't
> change jade to pug

- README.md
batman.js has been deprecated since 2014 and is no longer maintained, as explain here https://engineering.shopify.com/blogs/engineering/rebuilding-the-shopify-admin-improving-developer-productivity-by-deleting-28-000-lines-of-javascript
> Remove batman.js (deprecated)

- README.md
Timeline v3 and Timesheet.js are moved to new Github Repos, hence updating the URLs.
> Updating links to point to the latest versions.

- README.md
Hello,
I was checking some links in the machine learning section and noticed the deeplearn.js library.
But deeplearn.js became part of Tensorflow ecosystem and changed its name to tensorflow.js.
So I'm making the pull request to update this library and also add a new machine learning library.
> Add machine learning links

- README.md
MapCountdown is a browser library which shows countdown on top of the Google Maps
> docs: Add map-countdown

- README.md
1) Fixed markdown urls - removed space between ']' and '(' for a few urls.
2) Removed unnecessary space between '-' and description text.
3) Changed 'javascript|Javascript' to proper case ('JavaScript').
4) Fixed typos in a few words.
5) Added period at the very end of description (according contribution.md)
6) Added missed description for a few items.
@sorrycc Do u maintain this repo stil? I see many PRs, not merged.
Anyway, I faced with a few mistakes, and decided to create PR also. But I see, there are 2 PRs which interact with the same files:
- https://github.com/sorrycc/awesome-javascript/pull/370 by @nodiscc - the same fix is in my PR (which is much wider in regards to syntax mistakes). 
- https://github.com/sorrycc/awesome-javascript/pull/323 - almost the same fixes I have. I see …
> Markdown Syntax fixes

- README.md
Add Gridsome - a Vue-powered static site generator for building CDN-ready websites for any headless CMS, local files or APIs.
> Add Gridsome

- README.md
Added a new topic called Pre-evaluate code at build time plugin with the link to the actual repository which is really cool to use node js code in any front end library or framework without using a node layer.
> Added new QA topic with link

- README.md
The tag `<canvas>` was not visible because markdown treated it as html.
> fix unintended html evaluation

- README.md
I believe this wrapper has several advantages over some of the classes listed.
- Concise file uploading.
- Its philosophy is to improve `Fetch API`, rather than create a new opinionated wrapper. It tries to stay as close as possible to vanilla fetch, fix inconsistencies and make code more modern and readable.
- Has a unified `data` property on request that automatically does the correct type for `GET` (params) and `POST` (body) behind the scenes.
> Add Fetch API wrapper

- README.md
Optic automatically documents and tests your APIs.
I think Optic is awesome because its super simple to use and lets you easily add docs to any project. For most api projects, maintaining and creating documentation is a pain, and optic greatly streamlines this process.
[Repo: opticdev/optic](https://github.com/opticdev/optic), [Homepage: useoptic.com](https://useoptic.com)
> Add Optic to List

- README.md
I know that `Ramda` is already part of the list, so I will accept if you consider the inclusion of `Rambda` to be confusing to your visitors.
> Add Rambda to functional programming section

- README.md
Checklist:
---
I feel that old-established tools for synchronizing translation-files are still lacking, especially for JSON-based translations.
Therefore, I propose to add https://github.com/fkirc/attranslate to the list.
> add attranslate to I18n And L10n

- README.md
Removed mesh.js as it's archived, no longer maintained and author advises to not use it in production.
> Remove mesh.js

- README.md
Checklist:
---
The link to the `ramda` library was pointed to a fork of the original repository. The same has been updated with the proper link.
Old: [ramda](https://github.com/CrossEye/ramda)
New: [ramda](https://github.com/ramda/ramda)
> Updated the link to ramda

- README.md
> added next.js

- README.md
> Propose sweet-monads library into Functional Programming section

- README.md
Checklist:
---
**bundle** is an online tool to quickly and easily bundle your projects and see the minified and gzipped size, it's similar to bundlephobia but does all the work locally on your computer and can treeshake multiple packages (both commonjs and esm) into a bundle, it does all this via esbuild-wasm and rollup. I belive other people will benefit from it, so I am posting it here.
The repo is located here https://github.com/okikio/bundle
> add bundle.js.org to bundlers

- .github/workflows/validator.yml
1. Updated GitHub Actions versions:
actions/checkout@v2 → actions/checkout@v4
actions/upload-artifact@v2 → actions/upload-artifact@v4
Updated Ruby version from 2.6 to 3.2 (since 2.6 is no longer supported).
2. Optimized workflow steps:
Moved setup-ruby after checkout for better execution order.
Added bundler-cache: true to setup-ruby to prevent redundant gem installations.
3. Improved awesome_bot installation:
Added --no-document flag to speed up installation.
4. Made validation step more resilient:
Added continue-on-error: true to validate to prevent workflow failure on link errors.
5. Adjusted artifact handling: Used if: ${{ failure() }} to ensure artifacts are uploaded only if the validation fails.
Checklist:
---
...
> chore(ci): update GitHub Actions and Ruby version

- README.md
Added Regulex, a JavaScript regular expression visualizer, to the RegExp section.   Regulex provides an interactive way to understand regex patterns and their structure.
Checklist:
---
...
> docs(regexp): add Regulex JavaScript RegExp visualizer

- README.md
`Supertest` is a popular HTTP assertion library for testing REST APIs, often used with other testing frameworks like Mocha or Jest
Checklist:
---
...
> docs(assertion): add Supertest JavaScript assertion library

- README.md
Checklist:
---
...
This PR adds [ws](https://github.com/websockets/ws). The most popular and widely researched websocket for Node. js.
**STATS**
22.1k stars
Forks
[ 2.5k forks](https://github.com/websockets/ws/forks)
Used by
[24.7m](https://github.com/websockets/ws/network/dependents)
> feat: Add ws to Websockets section

- README.md
Checklist:
---
...
This PR adds openai to the sdk section. It is the official JavaScript / TypeScript library for the OpenAI API.  
The  repository is actively maintained and has over 8.5k stars and 3million weekly downloads
.
> feat: this commit adds openAI sdk to the sdk section

- README.md
Checklist:
---
[bun](https://github.com/oven-sh/bun)
Currently has 80k+ stars on GitHub, actively maintained, and a vibrant community.
> Add package manager bun

- README.md
Checklist:
---
...
This PR add Objection.js ORM to the ORM section.
Objection.js is an [ORM](https://en.wikipedia.org/wiki/Object-relational_mapping) for [Node.js](https://nodejs.org/) that aims to stay out of your way and make it as easy as possible to use the full power of SQL and the underlying database engine while still making the common stuff easy and enjoyable.
> Add objection js to orm
